### ISSUE TITLE
Not an image!

### ISSUE THREAD

**Issue by PhenomAmd** [ondrejvrabel/imup#1]
installed LAMP on my ubuntu server i have set 777 permissions to all files and whenever i try to upload an img i keep getting  that message 

is there anything else i need to do? like creating a folder or something?? 

message
![imup](https://user-images.githubusercontent.com/43511497/46504177-5ceb4f80-c7ea-11e8-95a0-8bb2d4168a81.png)

current web directory
![imup2](https://user-images.githubusercontent.com/43511497/46504098-2281b280-c7ea-11e8-8f3f-5e79c0f9a550.png)

could you please tell me what am i doing wrong?

**Comment by ondrejvrabel** [comment]
Sorry for late reply, you should create directory named "i" for the images.
